# Generated by Django 4.1 on 2023-02-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('experience_years', models.IntegerField()),
                ('role', models.CharField(choices=[('', 'Select your current role'), ('1', 'Student'), ('2', 'Full time Job'), ('3', 'Part Time Job'), ('4', 'Freelance'), ('5', 'Prefer not to say'), ('6', 'Other')], default='', max_length=35)),
            ],
        ),
    ]
