# Generated by Django 4.1 on 2023-02-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyform',
            name='back_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyform',
            name='customer_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyform',
            name='design',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyform',
            name='devOps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyform',
            name='front_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyform',
            name='full_stack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyform',
            name='management_finance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyform',
            name='other_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyform',
            name='product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyform',
            name='sales_marketing',
            field=models.BooleanField(default=False),
        ),
    ]
