# Generated by Django 4.1 on 2023-02-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_surveyform_back_end_surveyform_customer_support_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyform',
            name='like_survey',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes, I like it!'), ('no', 'No, it could be better')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='surveyform',
            name='back_end',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='surveyform',
            name='customer_support',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='surveyform',
            name='design',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='surveyform',
            name='devOps',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='surveyform',
            name='front_end',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='surveyform',
            name='full_stack',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='surveyform',
            name='management_finance',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='surveyform',
            name='other_remote',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='surveyform',
            name='product',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='surveyform',
            name='sales_marketing',
            field=models.BooleanField(),
        ),
    ]
